/*A mandatory relationship is a relationship in which a record in the primary table must have a 
corresponding record in the related table. In the provided SQL statements, the foreign key 
constraints on the "ARTISTS" table's "A_STYLEOFART" column and the "CUSTOMERS" table's "CUSTOMER_COUNTRYID" column are mandatory relationships. 
This is because these foreign key constraints enforce that every artist must have a corresponding record in the "TYPE_OF_ART" table and every 
customer must have a corresponding record in the "COUNTRY" table. In other words, these columns cannot contain null values.*/

CREATE TABLE TYPE_OF_ART 
   (	TOA_ID NUMBER(*,0) NOT NULL ENABLE, 
	ART_TYPE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT TYPE_OF_ART_PK PRIMARY KEY (TOA_ID)
   );

CREATE TABLE ARTISTS   (
	A_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	A_BIRTHPLACE VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	A_AGE NUMBER(*,0) NOT NULL ENABLE, 
	A_STYLEOFART NUMBER(*,0)  NOT NULL ENABLE, 
	 CONSTRAINT ARTISTS_PK PRIMARY KEY (A_NAME),
	CONSTRAINT ARTISTS_FK1 FOREIGN KEY (A_STYLEOFART)
	  REFERENCES TYPE_OF_ART (TOA_ID) ENABLE
);


CREATE TABLE COUNTRY 
   (	COUNTRY_ID NUMBER(*,0) NOT NULL ENABLE, 
	COUNTRY_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT COUNTRY_PK PRIMARY KEY (COUNTRY_ID)
     );

CREATE TABLE CUSTOMERS (
    CUSTOMER_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    CUSTOMER_ADDRESS VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    CUSTOMER_AMOUNTSPENT NUMBER, 
    CUSTOMER_COUNTRYID NUMBER,
     CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_NAME),
     CONSTRAINT FK_CC FOREIGN KEY (CUSTOMER_COUNTRYID) 
        REFERENCES COUNTRY(COUNTRY_ID)
);

CREATE TABLE PIECESOFART 
   (	ARTIST VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	YEAR VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	TITLE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	TYPE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PRICE NUMBER NOT NULL ENABLE, 
	CUSTOMERNAME VARCHAR2(20 BYTE), 
	 CONSTRAINT PIECESOFART_PK PRIMARY KEY (TITLE),
	 CONSTRAINT PIECESOFART_FK1 FOREIGN KEY (CUSTOMERNAME)
	  REFERENCES CUSTOMERS (CUSTOMER_NAME) ENABLE
   );
   
CREATE TABLE ARTISTS_MAKE_PIECESOFART (
	ARTIST_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PIECEOFART_TITLE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT ARTISTS_MAKE_PIECESOFART_PK PRIMARY KEY (ARTIST_NAME, PIECEOFART_TITLE),
  	 CONSTRAINT ARTISTS_MAKE_PIECESOFART_FK1 FOREIGN KEY (ARTIST_NAME)
	  REFERENCES ARTISTS (A_NAME) ENABLE, 
	 CONSTRAINT ARTISTS_MAKE_PIECESOFART_FK2 FOREIGN KEY (PIECEOFART_TITLE)
	  REFERENCES PIECESOFART (TITLE) ENABLE
   ) ;
CREATE TABLE CUSTOMER_FOLLOWS_ARTISTS   (	
             C_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	AR_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT CUSTOMER_FOLLOWS_ARTISTS_PK PRIMARY KEY (C_NAME, AR_NAME),
 	 CONSTRAINT CUSTOMER_FOLLOWS_ARTISTS_FK1 FOREIGN KEY (C_NAME)
	  REFERENCES CUSTOMERS (CUSTOMER_NAME) ENABLE, 
	 CONSTRAINT CUSTOMER_FOLLOWS_ARTISTS_FK2 FOREIGN KEY (AR_NAME)
	  REFERENCES ARTISTS (A_NAME) ENABLE
   );
   
   CREATE TABLE Art_GROUP  (
	GROUPNAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT ART_GROUP_PK PRIMARY KEY (GROUPNAME)
);

CREATE TABLE CUSTOMER_FOLLOWS_GROUPS  (
	CUS_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	GRP_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT CUSTOMER_FOLLOWS_GROUPS_PK PRIMARY KEY (CUS_NAME, GRP_NAME),
  	CONSTRAINT CUSTOMER_FOLLOWS_GROUPS_FK1 FOREIGN KEY (CUS_NAME)
	  REFERENCES CUSTOMERS (CUSTOMER_NAME) ENABLE, 
	 CONSTRAINT CUSTOMER_FOLLOWS_GROUPS_FK2 FOREIGN KEY (GRP_NAME)
	  REFERENCES Art_GROUP (GROUPNAME) ENABLE
);



CREATE TABLE PART_BELOGS_GROUP 
   (	PA_TITLE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	GR_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT PART_BELOGS_GROUP_PK PRIMARY KEY (PA_TITLE, GR_NAME),
  	CONSTRAINT PART_BELOGS_GROUP_FK1 FOREIGN KEY (PA_TITLE)
	  REFERENCES PIECESOFART (TITLE) ENABLE, 
	 CONSTRAINT PART_BELOGS_GROUP_FK2 FOREIGN KEY (GR_NAME)
	  REFERENCES Art_GROUP (GROUPNAME) ENABLE
);




