-- SHOWS CUSTOMERS FROM RUSSIA OR POLAND AND AMOUNT SPENT IS GREATER THAN THE AVERAGE AMOUNT SPENT 

SELECT C.CUSTOMER_NAME, CO.COUNTRY_NAME, C.CUSTOMER_AMOUNTSPENT
FROM CUSTOMERS C
INNER JOIN COUNTRY CO
ON C.CUSTOMER_COUNTRYID = CO.COUNTRY_ID
WHERE CO.COUNTRY_NAME = 'Russia'
OR CO.COUNTRY_NAME = 'Poland'
AND C.CUSTOMER_AMOUNTSPENT > (
    SELECT AVG(CUSTOMER_AMOUNTSPENT)
    FROM CUSTOMERS);


SELECT AVG(CUSTOMER_AMOUNTSPENT)
FROM CUSTOMERS;

--  The most expenisve piece of art and it's artist 

SELECT A.A_NAME, P.PRICE, P.TITLE
FROM ARTISTS A
INNER JOIN artists_make_piecesofart AM
ON A.A_NAME = AM.Artist_name
INNER JOIN PIECEsOFART P
ON AM.PIECEofart_TITLE = P.TITLE
WHERE P.PRICE =
    (SELECT MAX(PRICE)
        FROM PIECESOFART)

-- Artists with at least 3 followers

SELECT A.A_NAME, A.A_STYLEOFART, COUNT(C.C_NAME) AS FOLLOWERS
FROM ARTISTS A
LEFT JOIN CUSTOMER_FOLLOWS_ARTISTS C
ON A.A_NAME = C.AR_NAME
GROUP BY A.A_NAME, A.A_STYLEOFART
HAVING COUNT(C.C_NAME) > 2
ORDER BY FOLLOWERS DESC

-- Showing a list of artists between the age of 20 and 30 in ascending order

SELECT A_NAME, A_AGE 
FROM ARTISTS
WHERE A_AGE > 20
AND A_AGE < 30
ORDER BY A_AGE

-- DISPLAYS INFORMATION ABOUT ARTISTS WHO HAVE FOLLOWERS (CORRELATED SUBQUERY)
SELECT * FROM ARTISTS 
WHERE EXISTS 
    (SELECT AR_NAME FROM CUSTOMER_FOLLOWS_ARTISTS C 
    WHERE ARTISTS.A_NAME = C.AR_NAME);

-- It shows number of customers and sales per country
SELECT COUNTRY_NAME, COUNT(CUSTOMER_NAME) AS "NUMBER OF CUSTOMERS" , SUM(CUSTOMER_AMOUNTSPENT) AS SALES
FROM CUSTOMERS CU
LEFT JOIN COUNTRY CO
ON CU.CUSTOMER_COUNTRYID = CO.COUNTRY_ID
GROUP BY COUNTRY_NAME;
 
 -- SHOW YOUNGEST ARTIST WHO HAS A PIECE OF ART WORTH MORE THAN THE AVERAGE PRICE OF A PIECE OF ART

 SELECT A.A_NAME, A.A_AGE, P.TITLE, P.PRICE
FROM ARTISTS A
INNER JOIN ARTISTS_MAKE_PIECESOFART AMP
ON A.A_NAME = AMP.ARTIST_NAME
INNER JOIN PIECESOFART P
ON P.TITLE = AMP.PIECEOFART_TITLE
WHERE A.A_AGE = 
    (SELECT MIN(A_AGE)
    FROM ARTISTS)
AND P.PRICE > 
    (SELECT AVG(PRICE)
    FROM PIECESOFART)

-- SHOW LIST OF ART GROUPS 

SELECT * FROM ART_GROUP


--To retrieve all customers who live in Turkey:
SELECT CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_AMOUNTSPENT 
FROM CUSTOMERS
WHERE EXISTS (SELECT 1 FROM COUNTRY WHERE CUSTOMERS.CUSTOMER_COUNTRYID = COUNTRY.COUNTRY_ID AND COUNTRY_NAME = 'Turkey');


--To retrieve all pieces of art that have not been sold:
SELECT ARTIST, YEAR, TITLE, TYPE, PRICE
FROM PIECESOFART
WHERE CUSTOMERNAME IS NULL;

--To retrieve all artists who work in the style of painting:
SELECT A_NAME, A_BIRTHPLACE, A_AGE
FROM ARTISTS
WHERE EXISTS (SELECT 1 FROM TYPE_OF_ART WHERE ARTISTS.A_STYLEOFART = TYPE_OF_ART.TOA_ID AND ART_TYPE = 'Painting');
--
---To retrieve the name, type of art and style of art of all pieces of art in the collection:
SELECT PIECESOFART.TITLE, PIECESOFART.TYPE, TYPE_OF_ART.ART_TYPE
FROM PIECESOFART
JOIN TYPE_OF_ART ON PIECESOFART.TYPE = TYPE_OF_ART.TOA_ID;
--
---To retrieve the name, address, and country of all customers who follow a specific artist:
SELECT CUSTOMERS.CUSTOMER_NAME, CUSTOMERS.CUSTOMER_ADDRESS, COUNTRY.COUNTRY_NAME
FROM CUSTOMERS
JOIN CUSTOMER_FOLLOWS_ARTISTS ON CUSTOMERS.CUSTOMER_NAME = CUSTOMER_FOLLOWS_ARTISTS.C_NAME
JOIN ARTISTS ON ARTISTS.A_NAME = CUSTOMER_FOLLOWS_ARTISTS.AR_NAME
JOIN COUNTRY ON CUSTOMERS.CUSTOMER_COUNTRYID = COUNTRY.COUNTRY_ID
WHERE ARTISTS.A_NAME = 'Deacon';


--To retrieve the name, birthplace, and style of art of all artists who have created a specific piece of art:
SELECT ARTISTS.A_NAME, ARTISTS.A_BIRTHPLACE, TYPE_OF_ART.ART_TYPE
FROM ARTISTS
JOIN ARTISTS_MAKE_PIECESOFART ON ARTISTS.A_NAME = ARTISTS_MAKE_PIECESOFART.ARTIST_NAME
JOIN PIECESOFART ON ARTISTS_MAKE_PIECESOFART.PIECEOFART_TITLE = PIECESOFART.TITLE
JOIN TYPE_OF_ART ON ARTISTS.A_STYLEOFART = TYPE_OF_ART.TOA_ID
WHERE PIECESOFART.TITLE = 'specific piece of art title';



-----To retrieve the name and style of art of all artists who have created at least one piece of art that has been sold for more than $5000:
SELECT ARTISTS.A_NAME, TYPE_OF_ART.ART_TYPE
FROM ARTISTS
JOIN ARTISTS_MAKE_PIECESOFART ON ARTISTS.A_NAME = ARTISTS_MAKE_PIECESOFART.ARTIST_NAME
JOIN PIECESOFART ON ARTISTS_MAKE_PIECESOFART.PIECEOFART_TITLE = PIECESOFART.TITLE
JOIN TYPE_OF_ART ON ARTISTS.A_STYLEOFART = TYPE_OF_ART.TOA_ID
WHERE PIECESOFART.PRICE > 5000;



--To retrieve the name, address and amount spent of all customers who have spent more than the average amount spent by customers in their country:
SELECT CUSTOMERS.CUSTOMER_NAME, CUSTOMERS.CUSTOMER_ADDRESS, CUSTOMERS.CUSTOMER_AMOUNTSPENT
FROM CUSTOMERS,
  (SELECT AVG(CUSTOMER_AMOUNTSPENT) AS AVG_AMOUNT, CUSTOMER_COUNTRYID
   FROM CUSTOMERS
   GROUP BY CUSTOMER_COUNTRYID) AVG_CUSTOMERS
WHERE CUSTOMERS.CUSTOMER_AMOUNTSPENT > AVG_CUSTOMERS.AVG_AMOUNT
AND CUSTOMERS.CUSTOMER_COUNTRYID = AVG_CUSTOMERS.CUSTOMER_COUNTRYID;



--To retrieve the total amount spent by all customers grouped by country:
SELECT COUNTRY.COUNTRY_NAME, SUM(CUSTOMER_AMOUNTSPENT) AS TOTAL_AMOUNT_SPENT
FROM CUSTOMERS
JOIN COUNTRY ON CUSTOMERS.CUSTOMER_COUNTRYID = COUNTRY.COUNTRY_ID
GROUP BY COUNTRY.COUNTRY_NAME;



----To retrieve the total number of customers who follow each artist and the average amount spent by those customers:
SELECT ARTISTS.A_NAME, COUNT(CUSTOMER_FOLLOWS_ARTISTS.C_NAME) AS NUM_CUSTOMERS, AVG(CUSTOMERS.CUSTOMER_AMOUNTSPENT) AS AVG_AMOUNT_SPENT
FROM ARTISTS
JOIN CUSTOMER_FOLLOWS_ARTISTS ON ARTISTS.A_NAME = CUSTOMER_FOLLOWS_ARTISTS.AR_NAME
JOIN CUSTOMERS ON CUSTOMER_FOLLOWS_ARTISTS.C_NAME = CUSTOMERS.CUSTOMER_NAME
GROUP BY ARTISTS.A_NAME;
